[env:codecell_c6]
platform = https://github.com/pioarduino/platform-espressif32.git#54.03.20
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -I src                       ; allow #include "config.h" from anywhere in src/

lib_deps =
    h2zero/NimBLE-Arduino@^2.1.0
    https://github.com/microbotsio/CodeCell.git

; Optional: makes lib_deps reproducible to a specific commit
; lib_deps =
;     https://github.com/microbotsio/CodeCell.git#<commit-sha>